#! /bin/csh 
#
# manipulate-2020 Unix shell
#
#
# Note: everything but the accommodation of obsolete options and 
# system dependent environment variables have been
# moved to manipulate-2020.prl
# 
#
setenv SYSTEMTYPE unix
# 
# AGENCY must be only 3 characters
#
#
setenv AGENCY snl
#
# check number of input arguments
#
#
if ( $#argv != 1) then
       echo "Usage: manipulate-2020 called with Invalid number of arguments"
       exit 1
else
       perl ./manipulate-2020.prl $1
endif
#

