#! /bin/csh 
#
# manipulate-2020_regression Unix shell
#
  echo ""
  echo "Usage: manipulate-2020_regression called with zero arguments"
  echo ""
#
# Note: Run regression tests for manipulate-2020 
#       Later, add a comparison of output files
#
setenv SYSTEMTYPE unix
# 
# AGENCY must be only 3 characters
#
setenv AGENCY snl
#
# check number of input arguments
#
if ( $#argv > 0) then
       echo "Usage: manipulate-2020_regression called with Invalid number of arguments $#argv"
else
       ./manipulate-2020 example_NJOY_groupr_convert 
       ./manipulate-2020 example_cross_section_covariance_verification 
       ./manipulate-2020 example_NJOY_groupr_response_convert  
       ./manipulate-2020 example_resp_unc_spectrum_averaged_response
       ./manipulate-2020 example_NJOY_groupr_spectrum_convert  
       ./manipulate-2020 example_response_fold                         
       ./manipulate-2020 example_NJOY_groupr_xsec_convert      
       ./manipulate-2020 example_spct_unc_spectrum_averaged_response
       ./manipulate-2020 example_NJOY_response_combination
       ./manipulate-2020 example_composite_uncertainty
endif
#
